apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hpa-example
  namespace: itsmetommy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hpa-example
    spec:
      containers:
      - name: hpa-example
        image: httpd
        ports:
        - name: http-port
          containerPort: 80
        resources:
          requests:
            cpu: 500m
